### ISSUE TITLE
Plan to support Ventura?

### ISSUE THREAD

**Issue by wilsonnkwan** [johnnynunez/Xiaomi-Mi-Air#283]
Plan to support Ventura?

**Comment by Rememorio** [comment]
I wonder, too. But this EFI file can be easily updated by OCAuxiliary Tools from the current OC version to OC v0.8.6. That's some panic after updating to Ventura. As I use itlwm v2.2.0-alpha for Ventura to replace the Wi-Fi kext, it works now.

**Comment by wilsonnkwan** [comment]
Care to share your set of files? Heh.

> I wonder, too. But this EFI file can be easily updated by OCAuxiliary Tools from the current OC version to OC v0.8.6. That's some panic after updating to Ventura. As I use itlwm v2.2.0-alpha for Ventura to replace the Wi-Fi kext, it works now.

**Comment by Rememorio** [comment]
> Care to share your set of files? Heh.
> 
> > I wonder, too. But this EFI file can be easily updated by OCAuxiliary Tools from the current OC version to OC v0.8.6. That's some panic after updating to Ventura. As I use itlwm v2.2.0-alpha for Ventura to replace the Wi-Fi kext, it works now.

I've released my backup in my [repository](https://github.com/Rememorio/Xiaomi-Mi-Air/releases/tag/v13.0-alpha). I've been using for 2 weeks and it quite meets my daily needs, although there are still some bugs, for example, it takes Wi-Fi a few minutes to start working after power on or rebooting. Perhaps it could be fixed by itlwm v2.2.0-stable version that has not been released yet.

**Comment by johnnynunez** [comment]
I have m1 max, i don't have this laptop anymore

**Comment by johnnynunez** [comment]
done
